services:

  frontend:
    container_name: tpms-frontend
    build:
      context: ./tpm2
      dockerfile: ../Dockerfile.frontend

    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  backend:
    container_name: tpms-backend
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    ports:
      - 8080:8080
